apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-sync-backend
  namespace: staging
  labels:
    app: bookmark-sync-backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmark-sync-backend
  template:
    metadata:
      labels:
        app: bookmark-sync-backend
        environment: staging
    spec:
      containers:
      - name: backend
        image: IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_ENV
          value: "staging"
        - name: SERVER_PORT
          value: "8080"
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: host
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: ghcr-secret